CREATE TABLE IF NOT EXISTS tb_jogador (
pk_codjogador INTEGER PRIMARY KEY AUTOINCREMENT,
nome TEXT NOT NULL,
senha TEXT NOT NULL DEFAULT '',
score INTEGER NOT NULL DEFAULT 0,
dinheiro INTEGER NOT NULL DEFAULT 0,
nivel INTEGER NOT NULL DEFAULT 0,
codskin INTEGER NOT NULL
)

